import os
import requests
import random

TOKEN = os.environ["TELEGRAM_TOKEN"]
CHAT_ID = os.environ["TELEGRAM_CHAT_ID"]

# چند جمله نمونه انگلیسی (می‌تونی هر روز اضافه‌اش کنی)
sentences = [
    "One of the most important skills a person can develop is the ability to listen carefully and understand different perspectives before making a decision.",
    "Traveling to new countries not only allows you to experience different cultures, but also teaches you to adapt to unexpected situations and challenges.",
    "I believe that learning a foreign language is one of the best ways to expand your mind and communicate with people from all around the world.",
    "Sometimes, the most valuable lessons in life come from our mistakes, and we must be willing to accept them and grow from the experience.",
    "Reading books about history or science can provide a deeper understanding of how the world works and why societies develop in certain ways.",
    "It is essential to balance work and personal life, because focusing too much on one aspect can negatively affect your overall happiness and health.",
    "Many people underestimate the importance of expressing gratitude on a daily basis, which can greatly improve relationships and mental well-being.",
    "When faced with a difficult problem, it is often helpful to break it into smaller steps and tackle each one methodically rather than trying to solve everything at once.",
    "Volunteering in your community not only helps others, but it also gives you a sense of purpose and the opportunity to learn new skills.",
    "Technology has transformed the way we live, but it is important to use it responsibly to avoid becoming too dependent on digital devices.",
    "Effective communication is not just about speaking clearly, but also about understanding the emotions and needs of the people you are talking to.",
    "People who set clear and achievable goals tend to be more successful, because they have a roadmap and can measure their progress regularly.",
    "Experiencing failure can be challenging, but it teaches resilience and helps individuals develop better problem-solving strategies in the future.",
    "Spending time in nature can have a calming effect on the mind and can improve mental health by reducing stress and anxiety levels.",
    "Developing creativity is not limited to artists; it can be cultivated in everyday life by approaching problems from different perspectives.",
    "Learning how to manage time efficiently allows people to accomplish more tasks, reduce stress, and have more opportunities for personal growth.",
    "Cultural events such as theater performances or music festivals help people connect with their community and appreciate diversity.",
    "Taking responsibility for your actions is a sign of maturity and helps build trust and respect in both personal and professional relationships.",
    "Watching documentaries and reading informative articles can broaden your understanding of global issues and current events.",
    "Maintaining a healthy lifestyle includes eating nutritious food, exercising regularly, and ensuring enough sleep for mental and physical well-being.",
    "Understanding other people's points of view is crucial in solving conflicts and reaching compromises in both work and social life.",
    "Some people believe that success is purely about hard work, while others argue that luck and opportunity play an equally important role.",
    "Spending time with friends and family is essential for emotional support and can help reduce feelings of loneliness and isolation.",
    "Participating in sports not only improves physical fitness but also teaches valuable lessons about teamwork and discipline.",
    "Being curious and asking questions encourages learning and helps develop critical thinking skills necessary for personal growth.",
    "Reading novels in a foreign language can improve vocabulary, grammar, and comprehension while making the learning process enjoyable.",
    "Traveling alone can be a powerful experience, teaching independence, self-reliance, and how to navigate unfamiliar environments confidently.",
    "Listening to podcasts or watching educational videos is a great way to gain knowledge about topics that interest you without leaving home.",
    "Sometimes, the best way to overcome fear is to face it gradually, step by step, while acknowledging the challenges involved.",
    "Learning to cook new recipes allows people to be creative, explore different cultures, and develop an important life skill.",
    "Maintaining friendships requires effort, including communication, understanding, and spending quality time together regularly.",
    "Attending workshops or seminars on topics of interest can provide valuable knowledge, networking opportunities, and motivation.",
    "Being organized in your daily life reduces stress and ensures that you can complete tasks more efficiently and effectively.",
    "Listening to music can influence mood, boost creativity, and even improve concentration while studying or working.",
    "Understanding environmental issues and adopting sustainable habits can contribute to preserving the planet for future generations.",
    "Engaging in debates and discussions encourages people to articulate their thoughts clearly and consider alternative viewpoints.",
    "Traveling to rural areas can provide a different perspective on life, showing people how communities live and work in diverse conditions.",
    "Learning a musical instrument can improve memory, coordination, and emotional expression while providing a creative outlet.",
    "Being patient and persistent is essential when learning a new skill, as progress often takes time and consistent effort.",
    "Writing in a journal helps individuals reflect on their experiences, organize thoughts, and improve their self-awareness.",
    "Understanding the history of a country can help people appreciate its culture, traditions, and the challenges it has faced.",
    "Watching movies or reading literature in a foreign language helps learners understand context, idioms, and colloquial expressions.",
    "Developing empathy allows people to form stronger connections with others and enhances their social and emotional intelligence.",
    "Spending time volunteering abroad can teach new languages, skills, and provide insight into different cultures and lifestyles.",
    "Some people find meditation and mindfulness practices helpful for reducing anxiety and increasing focus in their daily life.",
    "Exploring career opportunities early in life helps individuals make informed decisions and discover their passions and strengths.",
    "Understanding economics and financial management is important for making responsible decisions about money and investments.",
    "Taking part in creative writing exercises can enhance imagination, expression, and language skills at the same time.",
    "Participating in community projects encourages teamwork, leadership, and a sense of belonging in a social environment.",
    "Experiencing different cuisines while traveling teaches people about culture, history, and traditions in an enjoyable way.",
    "Being able to give and receive constructive feedback is essential for personal growth, professional development, and learning.",
    "Reading biographies of successful people can inspire motivation, provide strategies, and offer insight into challenges and failures.",
    "Learning to prioritize tasks helps people manage time effectively, focus on important activities, and reduce stress levels.",
    "Engaging in outdoor activities, such as hiking or cycling, improves physical health and allows people to connect with nature.",
    "Understanding social etiquette and cultural norms is important when traveling or interacting with people from different backgrounds.",
    "Developing problem-solving skills enables individuals to face challenges creatively and find effective solutions to complex issues.",
    "Learning about psychology and human behavior helps people improve communication, relationships, and self-awareness.",
    "Participating in online courses provides access to knowledge from experts around the world without needing to attend in person.",
    "Spending time reflecting on personal values and goals helps people make better decisions and live a more fulfilling life.",
    "Exploring art galleries and museums enhances cultural knowledge and stimulates creativity and critical thinking.",
    "Learning to negotiate effectively can improve professional opportunities and help resolve conflicts in a positive manner.",
    "Keeping up with current events encourages awareness, critical thinking, and the ability to form informed opinions.",
    "Joining clubs or interest groups allows people to meet like-minded individuals and develop new skills and hobbies.",
    "Taking care of mental health is just as important as physical health, requiring mindfulness, relaxation, and support when needed.",
    "Learning about different religions and philosophies can help people appreciate diversity and respect other beliefs.",
    "Engaging in public speaking opportunities builds confidence, communication skills, and the ability to express ideas clearly.",
    "Understanding the impact of technology on society helps people use it responsibly and adapt to changes effectively.",
    "Spending time in reflection or meditation can enhance creativity, focus, and emotional balance in daily life.",
    "Learning to manage stress through techniques such as exercise, meditation, or planning is essential for long-term well-being.",
    "Reading newspapers or journals helps people stay informed and develop analytical skills by evaluating different perspectives.",
    "Developing leadership skills requires practice, self-awareness, and the ability to motivate and guide others effectively.",
    "Exploring scientific discoveries helps people understand the world, ask questions, and think critically about evidence.",
    "Participating in language exchange programs is an effective way to practice speaking and improve fluency in a foreign language.",
    "Setting personal challenges encourages growth, perseverance, and the ability to overcome obstacles in life.",
    "Learning about history, culture, and politics of different countries can broaden perspectives and reduce prejudice.",
    "Being open to constructive criticism allows people to improve skills, knowledge, and personal performance over time.",
    "Spending time learning practical skills, such as first aid or cooking, is valuable for self-reliance and daily life.",
    "Joining debate clubs or discussion groups can improve confidence, critical thinking, and the ability to argue effectively.",
    "Understanding the principles of science and research allows people to make informed decisions and evaluate information critically.",
    "Engaging in creative hobbies such as painting, writing, or music helps individuals express emotions and develop talent.",
    "Traveling with friends or family strengthens relationships, creates memories, and teaches teamwork and compromise.",
    "Learning about nutrition and healthy habits helps people maintain energy, focus, and overall physical and mental health.",
    "Understanding environmental issues encourages people to adopt sustainable lifestyles and protect natural resources.",
    "Practicing mindfulness while performing daily tasks can improve focus, reduce stress, and increase satisfaction in life.",
    "Learning to code or understand technology enhances problem-solving skills and opens up opportunities in the digital world.",
    "Participating in charity events and social work fosters empathy, gratitude, and a sense of responsibility in society.",
    "Understanding different communication styles helps people interact effectively with diverse personalities and cultures.",
    "Spending time outdoors and in nature has proven benefits for mental health, creativity, and physical well-being.",
    "Learning time management strategies ensures people can complete important tasks efficiently and have time for relaxation.",
    "Engaging in storytelling or creative writing encourages imagination, expression, and critical thinking skills simultaneously.",
    "Studying philosophy and ethics provides insights into human behavior, moral dilemmas, and the basis for decision-making.",
    "Traveling off the beaten path allows people to explore authentic local culture, develop problem-solving skills, and be adaptable.",
    "Participating in competitions or challenges motivates personal growth, resilience, and determination to succeed.",
    "Learning to summarize, paraphrase, and explain complex ideas clearly is crucial for effective communication skills.",
    "Developing a routine for self-improvement, such as reading, writing, or learning new skills, leads to continuous growth.",
    "Being curious and asking thoughtful questions encourages learning, creativity, and a deeper understanding of the world"
]


sentence = random.choice(sentences)
url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"

requests.post(url, json={"chat_id": CHAT_ID, "text": sentence})
